version: "3"
services:
  db01:
    image: vprocontainers/vprofiledb
    container_name: db01
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  mc01:
    image: memcached
    container_name: mc01
    ports:
      - "11211:11211"
    depends_on:
      - db01  

  rmq01:
    image: rabbitmq
    container_name: rmq01
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  app01:
    image: vprocontainers/vprofileapp
    container_name: app01
    ports:
      - "8080:8080"
    volumes: 
      - appdata:/usr/local/tomcat/webapps
    depends_on:
      - db01  

  lb01:
    image: vprocontainers/vprofileweb
    container_name: web01
    ports:
      - "80:80"
    depends_on:
      - app01

volumes:
  dbdata:
  appdata: